name: tfbc
description: "The Flutter Book Club official website"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  flex_color_scheme:
  flutter_riverpod:

  go_router:

  responsive_framework:


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  

  fonts:
    - family: Ransom
      fonts:
        - asset: assets/fonts/ransom.ttf
          weight: 700
    - family: EB_Garamond
      fonts:
        - asset: assets/fonts/EBGaramond-Regular.ttf
          weight: 400
        - asset: assets/fonts/EBGaramond-Medium.ttf
          weight: 500
        - asset: assets/fonts/EBGaramond-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EBGaramond-Bold.ttf
          weight: 700
  